Revert "Fix logic"
This reverts commit 57d9651b93a47413d9052094d8ef780ba4f23f36.

diff --git a/.github/actions/tools/terraform/action.yml b/.github/actions/tools/terraform/action.yml
--- a/.github/actions/tools/terraform/action.yml
+++ b/.github/actions/tools/terraform/action.yml
@@ -54,24 +54,19 @@ runs:
           "${{ inputs.working-directory }}/terraform"
         )
         echo "Searching for Terraform version in directories: ${dirs[*]}"
-        found_version=""
         for dir in "${dirs[@]}"; do
           echo "Checking directory: $dir"
           if [ -d "$dir" ]; then
             version=$(grep -rEho 'required_version *= *"[^"]+"' "$dir" --include \*.tf | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
             if [ -n "$version" ]; then
+              echo "Found Terraform version: $version"
               echo "TERRAFORM_VERSION=$version" >> $GITHUB_ENV
-              found_version="$version"
               break
             fi
           fi
         done
-        if [ -z "$found_version" ]; then
-          echo "No Terraform version found in specified directories."
-          echo "TERRAFORM_VERSION=latest" >> $GITHUB_ENV
-        else
-          echo "Using Terraform version: $found_version"
-        fi
+        echo "::error title=Terraform version not found::Could not determine required Terraform version."
+        exit 1
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
