Bug: replace version API with finding correct service account id (#17)

diff --git a/.github/actions/deployment/static-files/upload-build-to-s3/action.yml b/.github/actions/deployment/static-files/upload-build-to-s3/action.yml
--- a/.github/actions/deployment/static-files/upload-build-to-s3/action.yml
+++ b/.github/actions/deployment/static-files/upload-build-to-s3/action.yml
@@ -25,15 +25,13 @@ inputs:
 runs:
   using: composite
   steps:
-    # We can remove this in the future as we only use this to find the bucket name of the service account
-    - name: Find S3 Service Account Bucket Name
-      id: find-latest-s3-artifact
+    - name: Get AWS_ACCOUNT_ID environment variable of Service Account
+      id: find-service-account-id
       uses: nsbno/platform-actions/.github/actions/helpers/make-aws-api-call@v2
       with:
         http-method: GET
-        # using '/lambda' is a bit misleading, but it just means the version is set before Terraform runs
-        endpoint: https://version-handler.vydeployment.vydev.io/v2/versions/${{inputs.github-repository-name}}/lambda?working_directory=${{inputs.working-directory}}
-        continue-on-error: false
+        endpoint: https://enroll.vydeployment.vydev.io/environment_accounts
+        continue-on-error: true
 
     - name: Download and unzip artifact from S3
       shell: bash
@@ -42,8 +40,16 @@ runs:
         WORKING_DIRECTORY: ${{ inputs.working-directory }}
         GIT_SHA: ${{ inputs.git-sha }}
       run: |
-        SERVICE_BUCKET_NAME=$(echo '${{ steps.find-latest-s3-artifact.outputs.response }}' | jq -r '.bucket_name')
+        OWNER_ACCOUNT_ID=$(echo '${{ steps.find-service-account-id.outputs.response }}' | jq -r '.owner_account_id')
 
+        if [ -z "$OWNER_ACCOUNT_ID" ] || [ "$OWNER_ACCOUNT_ID" = "null" ]; then
+          echo "::error::Failed to find project AWS Service Account ID. This should not happen, contact Team Utviklerplattform. Response: ${{ steps.find-service-account-id.outputs.response }}"
+          exit 1
+        fi
+
+        # The service artifact bucket is in the same format for every account.
+        SERVICE_BUCKET_NAME="${OWNER_ACCOUNT_ID}-deployment-delivery-pipeline-artifacts"
+  
         # Build S3 object path
         if [ -n "$WORKING_DIRECTORY" ]; then
           S3_OBJECT_PATH="${GIT_REPO_NAME}/${WORKING_DIRECTORY}/${GIT_SHA}.zip"
