Delete based on log group name

diff --git a/.github/workflows/deployment.preview-cleanup.yml b/.github/workflows/deployment.preview-cleanup.yml
--- a/.github/workflows/deployment.preview-cleanup.yml
+++ b/.github/workflows/deployment.preview-cleanup.yml
@@ -24,9 +24,12 @@ jobs:
           role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_DEPLOYMENT_ROLE_NAME }}"
 
       - name: Delete App Runner Service
+        id: delete-service
         shell: bash
         run: |
           SERVICE_NAME="pr-${{ github.event.number }}-${{ inputs.service-name }}"
+          echo "service-name=$SERVICE_NAME" >> $GITHUB_OUTPUT
+
           SERVICE_ARN=$(aws apprunner list-services --region ${{ vars.AWS_REGION }} \
             --query "ServiceSummaryList[?ServiceName=='${SERVICE_NAME}'].ServiceArn" --output text)
           if [ -n "$SERVICE_ARN" ]; then
@@ -39,5 +42,21 @@ jobs:
       - name: Delete CloudWatch Logs
         shell: bash
         run: |
-          LOG_GROUP="/aws/apprunner/${SERVICE_NAME}"
-          aws logs delete-log-group --log-group-name "$LOG_GROUP" --region ${{ vars.AWS_REGION }} || echo "Log group not found: $LOG_GROUP"
+          PREFIX="/aws/apprunner/${{steps.delete-service.outputs.service-name}}"
+
+          LOG_GROUPS=$(aws logs describe-log-groups \
+            --log-group-name-prefix "$PREFIX" \
+            --query "logGroups[*].logGroupName" \
+            --output text)
+          echo "The following log groups will be deleted:"
+          echo "$LOG_GROUPS" | tr '\t' '\n'
+          
+          for LOG_GROUP in $LOG_GROUPS; do
+            echo "Deleting log group: $LOG_GROUP"
+            aws logs delete-log-group --log-group-name "$LOG_GROUP" --region ${{ vars.AWS_REGION }} 
+            if [ $? -eq 0 ]; then
+              echo "Successfully deleted: $LOG_GROUP"
+            else
+              echo "Failed to delete: $LOG_GROUP"
+            fi
+          done
